Repository kowainik/relude, pull requests merged in 2018-07, with the labels that each got.

#1 Fix travis, refactor
  .gitignore
  .travis.yml
  CHANGES.md
  CODEOWNERS
  CONTRIBUTING.md
  LICENSE
  README.md
  appveyor.yml
  stack-7.10.3.yaml
  stack-8.0.2.yaml
  stack-8.4.2.yaml
  stack-liquid.yaml
  stack.yaml
  universum.cabal
Labels: CI, refactoring

#3 [#2] Remove microlens from dependencies
  CHANGELOG.md
  README.md
  src/Universum.hs
  src/Universum/Container/Class.hs
  universum.cabal
Labels: remove

#24 [#12] Remove liquid haskell
  CHANGELOG.md
  README.md
  src/Universum/Nub.hs
  src/Universum/Unsafe.hs
Labels: remove

#26 [#10] Remove VarArgs module
  CHANGELOG.md
  README.md
  benchmark/Main.hs
  src/Universum.hs
  src/Universum/VarArg.hs
  universum.cabal
Labels: remove

#25 [#9] Remove safe-exceptions
  CHANGELOG.md
  README.md
  src/Universum/Exception.hs
  universum.cabal
Labels: reexport, remove

#28 [#11] Remove TypeOps module and type-operators dependency
  CHANGELOG.md
  README.md
  src/Universum.hs
  src/Universum/TypeOps.hs
  universum.cabal
Labels: reexport, remove

#27 [#7] Replace Container with Foldable
  CHANGELOG.md
  README.md
  benchmark/Main.hs
  src/Universum.hs
  src/Universum/Base.hs
  src/Universum/Container/Class.hs
  src/Universum/Foldable.hs
  src/Universum/Foldable/Fold.hs
  src/Universum/Foldable/Reexport.hs
  src/Universum/List/Safe.hs
  src/Universum/Monad.hs
  src/Universum/Monad/Container.hs
  test/Test/Universum/Property.hs
  universum.cabal
Labels: refactoring

#30 [#6] Drop support for GHC-7.10.3
  .travis.yml
  src/Universum/Base.hs
  src/Universum/Container/Class.hs
  src/Universum/Debug.hs
  src/Universum/Exception.hs
  src/Universum/Foldable/Fold.hs
  src/Universum/Lifted/File.hs
  src/Universum/List/Reexport.hs
  src/Universum/List/Safe.hs
  src/Universum/Monad.hs
  src/Universum/Monad/Reexport.hs
  src/Universum/Monoid.hs
  src/Universum/String/Conversion.hs
  test/Doctest.hs
  universum.cabal
Labels: refactoring

#29 [#13] Clean up functions and modules
  CHANGELOG.md
  src/Universum/Exception.hs
  src/Universum/Lifted.hs
  src/Universum/Lifted/Exit.hs
  src/Universum/Lifted/File.hs
  src/Universum/Lifted/ST.hs
  src/Universum/List/Safe.hs
  universum.cabal
Labels: refactoring, remove

#31 [#16] Add, rename whenLeft* whenRight* functions
  .hlint.yaml
  CHANGELOG.md
  README.md
  src/Universum/Monad/Either.hs
  src/Universum/String/Conversion.hs
Labels: new, refactoring

#33 [#18] Add LazyStrict type class
  CHANGELOG.md
  README.md
  src/Universum/Functor/Fmap.hs
  src/Universum/List/Reexport.hs
  src/Universum/String/Conversion.hs
  src/Universum/String/Reexport.hs
Labels: new

#32 [#8] Add interfaces for Maps
  CHANGELOG.md
  src/Universum/Container.hs
  src/Universum/Container/Class.hs
  src/Universum/Container/Map.hs
  src/Universum/Container/One.hs
  src/Universum/Container/Reexport.hs
  universum.cabal
Labels: new, refactoring

#35 [#17] Add foldMapA and foldMapM functions
  CHANGELOG.md
  src/Universum/Foldable/Fold.hs
Labels: new

#37 [#14] Introduce *.Extra modules
  CHANGELOG.md
  src/Universum/Extra/Bifunctor.hs
  src/Universum/Extra/Enum.hs
  src/Universum/Extra/Group.hs
  universum.cabal
Labels: new

#36 [#20] Add viaNonEmpty function
  CHANGELOG.md
  README.md
  src/Universum/List/Safe.hs
Labels: new

#39 [#21] Add MonadFail instance for Either
  CHANGELOG.md
  src/Universum/Foldable/Fold.hs
  src/Universum/Monad/Either.hs
Labels: new

#38 [#15] Add instructions aboud base-noprelude
  README.md
Labels: doc

#42 [#5] Improve documentation
  .ghci
  .hlint.yaml
  .travis.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  benchmark/Main.hs
  relude.cabal
  src/Relude/Container.hs
  src/Relude/Extra/Group.hs
  src/Relude/Extra/Map.hs
  src/Relude/Function.hs
  test/Spec.hs
  test/Test/Relude/Property.hs
Labels: doc
