Repository kowainik/relude, pull requests merged in 2018-09, with the labels that each got.

#68 [#66] Reexport '>>>' and '<<<'
  .hlint.yaml
  CHANGELOG.md
  src/Relude/Function.hs
Labels: hlint, reexport

#71 [#59] Add flap and (??)
  CHANGELOG.md
  src/Relude/Functor/Fmap.hs
Labels: new

#72 [#64] Improve Foldable1 typeclass
  CHANGELOG.md
  README.md
  src/Relude/Extra/Foldable1.hs
Labels: doc, new, refactoring

#74 [#19] Rewrite hlint to Dhall
  .hlint.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  hlint/Rule.dhall
  hlint/hlint.dhall
  hlint/warn.dhall
  src/Relude/Lifted/Exit.hs
  src/Relude/List/NonEmpty.hs
  src/Relude/List/Reexport.hs
  test/Spec.hs
Labels: hlint

#75 [#67] Add HLint rules for put functions
  .hlint.yaml
  CHANGELOG.md
  README.md
  hlint/hlint.dhall
  hlint/warn.dhall
  relude.cabal
  src/Relude/Function.hs
  src/Relude/Functor/Reexport.hs
  src/Relude/Lifted/File.hs
  src/Relude/Lifted/Terminal.hs
  src/Relude/Print.hs
  src/Relude/String/Conversion.hs
Labels: hlint, refactoring

#76 [#61] Add binary newtype combinators
  CHANGELOG.md
  hlint/Rule.dhall
  src/Relude/Extra/Newtype.hs
  src/Relude/Foldable/Fold.hs
  src/Relude/Lifted.hs
  src/Relude/List/NonEmpty.hs
  src/Relude/Monad/Maybe.hs
  src/Relude/String/Conversion.hs
Labels: new, refactoring

#77 [#60] Add lifting to transformers functions
  .hlint.yaml
  CHANGELOG.md
  hlint/hlint.dhall
  src/Relude/Monad/Trans.hs
Labels: new

#78 [#22] Add monomorphic versions of file functions
  .hlint.yaml
  CHANGELOG.md
  README.md
  hlint/hlint.dhall
  relude.cabal
  src/Relude.hs
  src/Relude/File.hs
  src/Relude/Lifted/File.hs
Labels: new, refactoring

#84 [#23] Support ghc-8.6.1
  .travis.yml
  relude.cabal
Labels: CI
