Repository kowainik/relude, pull requests merged in 2018-08, with the labels that each got.

#45 [#44] Derive parsers from pretty-printers
  CHANGELOG.md
  relude.cabal
  src/Relude/Extra/Enum.hs
Labels: enhancement

#50 [#46] Add a function that returns its own name
  CHANGELOG.md
  relude.cabal
  src/Relude/Extra/CallStack.hs
Labels: enhancement

#51 [#43] Implement Relude.Extra.Newtype module
  CHANGELOG.md
  relude.cabal
  src/Relude/Extra/Newtype.hs
Labels: new

#52 Improve documentation
  README.md
  relude.cabal
  src/Relude/Container/One.hs
  src/Relude/Extra/CallStack.hs
Labels: doc

#53 [#49] Speed up and refactor property tests
  CHANGELOG.md
  relude.cabal
  test/Test/Relude/Property.hs
Labels: refactoring, tests

#55 [#48] More reexports from base
  CHANGELOG.md
  src/Relude/Functor/Fmap.hs
  src/Relude/Monad/Either.hs
Labels: reexport, refactoring

#57 [#54] Improve documentation
  CHANGELOG.md
  LICENSE
  README.md
  relude.cabal
  src/Relude.hs
  src/Relude/Applicative.hs
  src/Relude/Base.hs
  src/Relude/Bool.hs
  src/Relude/Bool/Guard.hs
  src/Relude/Bool/Reexport.hs
  src/Relude/Container.hs
  src/Relude/Container/One.hs
  src/Relude/Container/Reexport.hs
  src/Relude/Debug.hs
  src/Relude/DeepSeq.hs
  src/Relude/Exception.hs
  src/Relude/Extra/Bifunctor.hs
  src/Relude/Extra/CallStack.hs
  src/Relude/Extra/Enum.hs
  src/Relude/Extra/Group.hs
  src/Relude/Extra/Map.hs
  src/Relude/Extra/Newtype.hs
  src/Relude/Foldable.hs
  src/Relude/Foldable/Fold.hs
  src/Relude/Foldable/Reexport.hs
  src/Relude/Function.hs
  src/Relude/Functor.hs
  src/Relude/Functor/Fmap.hs
  src/Relude/Functor/Reexport.hs
  src/Relude/Lifted.hs
  src/Relude/Lifted/Concurrent.hs
  src/Relude/Lifted/Exit.hs
  src/Relude/Lifted/File.hs
  src/Relude/Lifted/IORef.hs
  src/Relude/List.hs
  src/Relude/List/NonEmpty.hs
  src/Relude/List/Reexport.hs
  src/Relude/Monad.hs
  src/Relude/Monad/Either.hs
  src/Relude/Monad/Maybe.hs
  src/Relude/Monad/Reexport.hs
  src/Relude/Monad/Trans.hs
  src/Relude/Monoid.hs
  src/Relude/Nub.hs
  src/Relude/Print.hs
  src/Relude/String.hs
  src/Relude/String/Conversion.hs
  src/Relude/String/Reexport.hs
  src/Relude/Unsafe.hs
Labels: doc, reexport, remove, tests

#56 [#41] Add `Foldable1`
  CHANGELOG.md
  src/Relude/Extra/Foldable1.hs
  src/Relude/Extra/Newtype.hs
  src/Relude/Monad/Maybe.hs
Labels: enhancement, new

#65 [#63] Remove Print typeclass
  CHANGELOG.md
  README.md
  relude.cabal
  src/Relude/Debug.hs
  src/Relude/Print.hs
  src/Relude/String/Conversion.hs
Labels: new, remove
