Repository kowainik/relude, pull requests merged in 2018-10, with the labels that each got.

#88 Adds hlint rules for `asumMap`
  .hlint.yaml
  hlint/hlint.dhall
Labels: Hacktoberfest, hlint

#87 [#83] Pretty latex for function asymptotics
  src/Relude/Nub.hs
Labels: Hacktoberfest, doc

#90 Introduces a Relude.Extra.Type module, with a typeName function
  CHANGELOG.md
  relude.cabal
  src/Relude.hs
  src/Relude/Extra/Type.hs
Labels: Hacktoberfest, extra

#95 [#79] Add hlint rules for type class
  .hlint.yaml
  hlint/hlint.dhall
Labels: Hacktoberfest, hlint

#101 [#97] Added monadic version of (&&) and (||) operators
  CHANGELOG.md
  src/Relude/Bool/Guard.hs
Labels: Hacktoberfest, new

#102 Add reexports for 'Data.Bifoldable' and 'Data.Bitraversable'
  .hlint.yaml
  CHANGELOG.md
  hlint/hlint.dhall
  relude.cabal
  src/Relude/Foldable/Reexport.hs
Labels: Hacktoberfest, reexport

#105 Fix doctests in `Relude.Bool.Guard`
  src/Relude/Bool/Guard.hs
Labels: Hacktoberfest, doc, tests

#106 [#100] Add Validation data type to Extra modules
  CHANGELOG.md
  relude.cabal
  src/Relude.hs
  src/Relude/Extra/Validation.hs
Labels: Hacktoberfest, new

#104 [#103] drop utf8-string dependency
  CHANGELOG.md
  relude.cabal
  src/Relude/String/Conversion.hs
Labels: Hacktoberfest, refactoring, remove

#107 [#70] Reexported Data.Functor.Contravariant for GHC >= 8.6.1.
  CHANGELOG.md
  hlint/hlint.dhall
  src/Relude/Functor/Reexport.hs
Labels: Hacktoberfest, hlint, reexport

#111 Fix typo in readme
  README.md
Labels: doc
