Repository kowainik/relude, pull requests merged in 2019-03, with the labels that each got.

#149 [#136] Add HLint rules for Extra modules
  .hlint.yaml
  CHANGELOG.md
  hlint/hlint.dhall
Labels: hlint

#150 [#134] Describe way to run relude hlint rules on CI
  README.md
Labels: CI, doc

#151 [#146] Improve documentation
  .travis.yml
  CHANGELOG.md
  README.md
  relude.cabal
  src/Relude/File.hs
  src/Relude/Foldable/Fold.hs
  stack.yaml
Labels: CI, doc

#152 [#127] Add Lens module
  CHANGELOG.md
  relude.cabal
  src/Relude.hs
  src/Relude/Extra/Lens.hs
Labels: doc, enhancement, extra

#153 Prepare changelog for 0.5.0 release
  CHANGELOG.md
Labels: doc
