Repository kowainik/relude, pull requests merged in 2019-10, with the labels that each got.

#197 Documentation examples
  src/Relude/Debug.hs
  src/Relude/DeepSeq.hs
  src/Relude/Extra/Map.hs
  src/Relude/Extra/Newtype.hs
  src/Relude/Extra/Validation.hs
  src/Relude/File.hs
  src/Relude/Function.hs
  src/Relude/Lifted.hs
  src/Relude/Lifted/Exit.hs
  src/Relude/Lifted/IORef.hs
  src/Relude/Monad/Either.hs
  src/Relude/Monad/Maybe.hs
  src/Relude/Monad/Trans.hs
  src/Relude/Print.hs
  src/Relude/Unsafe.hs
Labels: doc

#198 [#187] Remove tasty* dependencies
  CHANGELOG.md
  relude.cabal
  test/Spec.hs
  test/Test/Relude/Property.hs
Labels: Hacktoberfest, tests

#199 [#148] Migrate custom HLint rules to a newer dhall spec
  hlint/hlint.dhall
  hlint/warn.dhall
Labels: hlint

#200 Reexport foldMap' from new enough versions
  CHANGELOG.md
  src/Relude/Foldable/Reexport.hs
Labels: Hacktoberfest, reexport

#202 Implement `bimapBoth` (#174)
  CHANGELOG.md
  src/Relude/Extra/Bifunctor.hs
  src/Relude/Extra/Tuple.hs
Labels: extra

#205 [ci skip] Fix typo
  README.md
Labels: doc

#204 Implement safe `at` (!!) function
  CHANGELOG.md
  benchmark/Main.hs
  src/Relude/Bool/Guard.hs
  src/Relude/List.hs
Labels: Hacktoberfest, new

#206 Add appveyor ci
  README.md
  appveyor.yml
  src/Relude/Foldable/Fold.hs
Labels: CI, Hacktoberfest

#207 203: Implement Guarded Combinator
  CHANGELOG.md
  src/Relude/Bool/Guard.hs
Labels: new

#208 Add GitHub Actions with cachix
  .github/workflows/ci.yml
  README.md
  default.nix
Labels: CI

#209 Implement type family Elem
  CHANGELOG.md
  src/Relude/Extra/Type.hs
Labels: extra, new

#211 [#154] Minor documentation improvements
  README.md
  benchmark/Main.hs
  src/Relude.hs
  src/Relude/Applicative.hs
  src/Relude/Base.hs
  src/Relude/Bool.hs
  src/Relude/Bool/Guard.hs
  src/Relude/Bool/Reexport.hs
  src/Relude/Container.hs
  src/Relude/Container/One.hs
  src/Relude/Container/Reexport.hs
  src/Relude/Debug.hs
  src/Relude/DeepSeq.hs
  src/Relude/Exception.hs
  src/Relude/Extra/Bifunctor.hs
  src/Relude/Extra/CallStack.hs
  src/Relude/Extra/Enum.hs
  src/Relude/Extra/Foldable.hs
  src/Relude/Extra/Foldable1.hs
  src/Relude/Extra/Group.hs
  src/Relude/Extra/Lens.hs
  src/Relude/Extra/Map.hs
  src/Relude/Extra/Newtype.hs
  src/Relude/Extra/Tuple.hs
  src/Relude/Extra/Type.hs
  src/Relude/Extra/Validation.hs
  src/Relude/File.hs
  src/Relude/Foldable.hs
  src/Relude/Foldable/Fold.hs
  src/Relude/Foldable/Reexport.hs
  src/Relude/Function.hs
  src/Relude/Functor.hs
  src/Relude/Functor/Fmap.hs
  src/Relude/Functor/Reexport.hs
  src/Relude/Lifted.hs
  src/Relude/Lifted/Concurrent.hs
  src/Relude/Lifted/Exit.hs
  src/Relude/Lifted/File.hs
  src/Relude/Lifted/IORef.hs
  src/Relude/Lifted/Terminal.hs
  src/Relude/List.hs
  src/Relude/List/NonEmpty.hs
  src/Relude/List/Reexport.hs
  src/Relude/Monad.hs
  src/Relude/Monad/Either.hs
  src/Relude/Monad/Maybe.hs
  src/Relude/Monad/Reexport.hs
  src/Relude/Monad/Trans.hs
  src/Relude/Monoid.hs
  src/Relude/Nub.hs
  src/Relude/Numeric.hs
  src/Relude/Print.hs
  src/Relude/String.hs
  src/Relude/String/Conversion.hs
  src/Relude/String/Reexport.hs
  src/Relude/Unsafe.hs
  test/Doctest.hs
  test/Spec.hs
  test/Test/Relude/Property.hs
Labels: doc

#212 [#171] Specify custom type errors for Text functions
  src/Relude/List/Reexport.hs
  src/Relude/String/Reexport.hs
Labels: doc

#216 Add property tests for the Validation type
  relude.cabal
  test/Test/Relude/Extra/Validation/Property.hs
  test/Test/Relude/Property.hs
Labels: tests

#217 Do not trigger HLint on laws
  test/Test/Relude/Extra/Validation/Property.hs
Labels: hlint

#218 Add new logo
  README.md
Labels: doc, enhancement

#190 Return Failure early in `<*` and `*>` too
  CHANGELOG.md
  src/Relude/Extra/Validation.hs
Labels: refactoring

#220 [#171] Foldable1 for Lists error
  src/Relude/Extra/Enum.hs
  src/Relude/Extra/Foldable.hs
  src/Relude/Extra/Foldable1.hs
  src/Relude/Extra/Validation.hs
  src/Relude/Foldable/Fold.hs
  src/Relude/String/Conversion.hs
  test/Doctest.hs
Labels: enhancement, extra

#219 [#171] Add custom type error for To* typeclasses
  src/Relude/Applicative.hs
  src/Relude/Monad/Either.hs
  src/Relude/String/Conversion.hs
  src/Relude/String/Reexport.hs
Labels: doc, enhancement

#223 [#214] Add `mapMaybeM`
  CHANGELOG.md
  src/Relude/Monad/Maybe.hs
Labels: new

#222 [#171] Add custom type errors in some places
  src/Relude/Debug.hs
  src/Relude/Extra/Foldable1.hs
  src/Relude/List/Reexport.hs
  src/Relude/String/Conversion.hs
Labels: doc, enhancement

#224 [#221] Refactor Validation module
  src/Relude/Extra/Validation.hs
Labels: doc, extra

#225 Prepare changelog for the 0.6.0.0 version
  CHANGELOG.md
  README.md
  src/Relude/Extra/Enum.hs
  src/Relude/Extra/Tuple.hs
Labels: doc

#226 Use latest Stackage snapshot
  .travis.yml
  src/Relude/DeepSeq.hs
  stack.yaml
Labels: CI
