Repository kowainik/relude, pull requests merged in 2019-09, with the labels that each got.

#184 [#164] Reexport ShortByteString
  .hlint.yaml
  CHANGELOG.md
  README.md
  hlint/hlint.dhall
  hlint/warn.dhall
  src/Relude/Container/One.hs
  src/Relude/String/Conversion.hs
  src/Relude/String/Reexport.hs
Labels: enhancement, reexport

#185 #167 rename (prec -> prev) & (dupe -> dup)
  .hlint.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  hlint/hlint.dhall
  src/Relude/Extra/Enum.hs
  src/Relude/Extra/Tuple.hs
Labels: extra, hlint

#162 Use foldr in place of explicit recursion and toList
  CHANGELOG.md
  src/Relude/Foldable/Fold.hs
Labels: enhancement

#183 [#182] Support GHC 8.8
  .travis.yml
  CHANGELOG.md
  relude.cabal
  src/Relude/Extra/Type.hs
  stack.yaml
Labels: CI, doc

#189 Use `$>` instead of `*>` and `pure` where possible
  CHANGELOG.md
  src/Relude/Extra/Enum.hs
  src/Relude/Extra/Map.hs
Labels: refactoring

#191 Implement `asumMap` and `foldMapA` by coercing `foldMap`
  CHANGELOG.md
  src/Relude/Foldable/Fold.hs
Labels: refactoring

#193 Implement `andM`, `orM`, `allM`, and `anyM` in terms of `&&^` and `||^`
  CHANGELOG.md
  src/Relude/Foldable/Fold.hs
Labels: refactoring

#194 Use `mapToFst` instead of `zip` to improve list fusion in `inverseMap`
  CHANGELOG.md
  src/Relude/Extra/Enum.hs
Labels: refactoring

#195 Implement `foldMap1` for `NonEmpty` in terms of `foldr`
  CHANGELOG.md
  src/Relude/Extra/Foldable1.hs
Labels: enhancement, refactoring

#186 [#173] Haddock Examples - WIP
  src/Relude/Debug.hs
  src/Relude/DeepSeq.hs
  src/Relude/Extra/Map.hs
  src/Relude/Extra/Newtype.hs
  src/Relude/Extra/Validation.hs
  src/Relude/File.hs
  src/Relude/Function.hs
  src/Relude/Lifted/Exit.hs
  src/Relude/Lifted/File.hs
  src/Relude/Lifted/IORef.hs
  src/Relude/Monad/Either.hs
  src/Relude/Monad/Maybe.hs
  src/Relude/Monad/Trans.hs
  src/Relude/Print.hs
  src/Relude/Unsafe.hs
Labels: doc
