Repository kowainik/relude, pull requests merged in 2019-02, with the labels that each got.

#137 Improve travis and docs
  .travis.yml
  CHANGELOG.md
  benchmark/Main.hs
  relude.cabal
  src/Relude.hs
  src/Relude/Applicative.hs
  src/Relude/Base.hs
  src/Relude/Bool.hs
  src/Relude/Bool/Guard.hs
  src/Relude/Bool/Reexport.hs
  src/Relude/Container.hs
  src/Relude/Container/One.hs
  src/Relude/Container/Reexport.hs
  src/Relude/Debug.hs
  src/Relude/DeepSeq.hs
  src/Relude/Exception.hs
  src/Relude/Extra/Bifunctor.hs
  src/Relude/Extra/CallStack.hs
  src/Relude/Extra/Enum.hs
  src/Relude/Extra/Foldable1.hs
  src/Relude/Extra/Group.hs
  src/Relude/Extra/Map.hs
  src/Relude/Extra/Newtype.hs
  src/Relude/Extra/Tuple.hs
  src/Relude/Extra/Type.hs
  src/Relude/Extra/Validation.hs
  src/Relude/File.hs
  src/Relude/Foldable.hs
  src/Relude/Foldable/Fold.hs
  src/Relude/Foldable/Reexport.hs
  src/Relude/Function.hs
  src/Relude/Functor.hs
  src/Relude/Functor/Fmap.hs
  src/Relude/Functor/Reexport.hs
  src/Relude/Lifted.hs
  src/Relude/Lifted/Concurrent.hs
  src/Relude/Lifted/Exit.hs
  src/Relude/Lifted/File.hs
  src/Relude/Lifted/IORef.hs
  src/Relude/Lifted/Terminal.hs
  src/Relude/List.hs
  src/Relude/List/NonEmpty.hs
  src/Relude/List/Reexport.hs
  src/Relude/Monad.hs
  src/Relude/Monad/Either.hs
  src/Relude/Monad/Maybe.hs
  src/Relude/Monad/Reexport.hs
  src/Relude/Monad/Trans.hs
  src/Relude/Monoid.hs
  src/Relude/Nub.hs
  src/Relude/Numeric.hs
  src/Relude/Print.hs
  src/Relude/String.hs
  src/Relude/String/Conversion.hs
  src/Relude/String/Reexport.hs
  src/Relude/Unsafe.hs
  stack.yaml
  test/Doctest.hs
  test/Spec.hs
  test/Test/Relude/Property.hs
Labels: CI, doc

#139 [#121] Reexport Ap and change foldMapA
  .hlint.yaml
  CHANGELOG.md
  hlint/hlint.dhall
  src/Relude/Foldable/Fold.hs
  src/Relude/Monoid.hs
Labels: reexport

#141 Fix README typo.
  README.md
Labels: doc

#142 [#138] + RealFloat
  CHANGELOG.md
  src/Relude/Numeric.hs
Labels: reexport

#145 [#144] Add `traverseToSnd` and friends to `Relude.Extra.Tuple`
  .hlint.yaml
  CHANGELOG.md
  hlint/hlint.dhall
  src/Relude/Extra/Tuple.hs
Labels: extra

#147 [#140] Improve compile-time error messages
  CHANGELOG.md
  relude.cabal
  src/Relude/Foldable/Fold.hs
Labels: enhancement
