Repository kowainik/relude, pull requests merged in 2020-05, with the labels that each got.

#258 Correct spelling in comments.
  src/Relude.hs
  src/Relude/Debug.hs
  src/Relude/Exception.hs
  src/Relude/Extra/CallStack.hs
  src/Relude/Extra/Foldable1.hs
  src/Relude/Extra/Lens.hs
  src/Relude/Extra/Map.hs
  src/Relude/Extra/Newtype.hs
  src/Relude/Extra/Validation.hs
  src/Relude/Monad/Either.hs
  src/Relude/Nub.hs
  src/Relude/Numeric.hs
  src/Relude/String.hs
  src/Relude/Unsafe.hs
Labels: doc

#262 Rename function for better spelling of "associativity"
  test/Test/Relude/Extra/Validation/Property.hs
Labels: refactoring

#266 Delete commented out code.
  src/Relude/Applicative.hs
Labels: refactoring

#272 [#233] Add 'etaReaderT' function
  CHANGELOG.md
  src/Relude/Monad/Trans.hs
Labels: new

#271 [#265] Add documentation sections to modules with reexports
  README.md
  src/Relude.hs
  src/Relude/Applicative.hs
  src/Relude/Base.hs
  src/Relude/Bool.hs
  src/Relude/Bool/Guard.hs
  src/Relude/Bool/Reexport.hs
  src/Relude/Container.hs
  src/Relude/Container/One.hs
  src/Relude/Container/Reexport.hs
  src/Relude/Debug.hs
  src/Relude/DeepSeq.hs
  src/Relude/Exception.hs
  src/Relude/Extra.hs
  src/Relude/Extra/Bifunctor.hs
  src/Relude/Extra/CallStack.hs
  src/Relude/Extra/Enum.hs
  src/Relude/Extra/Foldable.hs
  src/Relude/Extra/Foldable1.hs
  src/Relude/Extra/Group.hs
  src/Relude/Extra/Lens.hs
  src/Relude/Extra/Map.hs
  src/Relude/Extra/Newtype.hs
  src/Relude/Extra/Tuple.hs
  src/Relude/Extra/Type.hs
  src/Relude/Extra/Validation.hs
  src/Relude/File.hs
  src/Relude/Foldable.hs
  src/Relude/Foldable/Fold.hs
  src/Relude/Foldable/Reexport.hs
  src/Relude/Function.hs
  src/Relude/Functor.hs
  src/Relude/Functor/Fmap.hs
  src/Relude/Functor/Reexport.hs
  src/Relude/Lifted.hs
  src/Relude/Lifted/Concurrent.hs
  src/Relude/Lifted/Exit.hs
  src/Relude/Lifted/File.hs
  src/Relude/Lifted/IORef.hs
  src/Relude/Lifted/Terminal.hs
  src/Relude/List.hs
  src/Relude/List/NonEmpty.hs
  src/Relude/List/Reexport.hs
  src/Relude/Monad.hs
  src/Relude/Monad/Either.hs
  src/Relude/Monad/Maybe.hs
  src/Relude/Monad/Reexport.hs
  src/Relude/Monad/Trans.hs
  src/Relude/Monoid.hs
  src/Relude/Nub.hs
  src/Relude/Numeric.hs
  src/Relude/Print.hs
  src/Relude/String.hs
  src/Relude/String/Conversion.hs
  src/Relude/String/Reexport.hs
  src/Relude/Unsafe.hs
Labels: doc, enhancement, refactoring

#273 [#244] Remove DEPRECATED 'prec', 'dupe', 'mapBoth'
  CHANGELOG.md
  src/Relude/Extra/Enum.hs
  src/Relude/Extra/Tuple.hs
Labels: refactoring, remove

#275 [#256] Fix partiality in 'cycle'
  CHANGELOG.md
  src/Relude/List/Reexport.hs
Labels: enhancement

#274 [#228] Implement `universeNonEmpty`
  CHANGELOG.md
  src/Relude/Extra/Enum.hs
  src/Relude/Monad/Trans.hs
Labels: extra, new

#276 [#234] scan{l,r}1
  CHANGELOG.md
  hlint/hlint.dhall
  src/Relude/List/Reexport.hs
Labels: enhancement, reexport

#277 [#246] Deprecate 'Relude.Extra.Validation' in favour of validation-selective
  CHANGELOG.md
  README.md
  src/Relude.hs
  src/Relude/Extra.hs
  src/Relude/Extra/Validation.hs
Labels: extra, remove

#278 [#264] Support latest Dhall spec
  .hlint.yaml
  README.md
  hlint/warn.dhall
  test/Spec.hs
Labels: hlint

#279 [#229] Minor documentation improvements: part2
  README.md
  src/Relude/Bool/Guard.hs
  src/Relude/Foldable/Fold.hs
Labels: doc

#282 Improve README a bit more
  README.md
  src/Relude.hs
Labels: doc

#284 [#283] Add String-types conversion table
  src/Relude/String.hs
Labels: doc

#287 More documentation improvements
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  relude.cabal
  src/Relude/Unsafe.hs
Labels: doc

#288 [#281] Move One property tests from 'doctest' to 'hedgehog'
  relude.cabal
  src/Relude/Container/One.hs
  test/Test/Relude/Container/One.hs
  test/Test/Relude/Gen.hs
  test/Test/Relude/Property.hs
Labels: doc, tests

#289 [#196] Rename and deprecate `mapToFst/Snd`
  .hlint.yaml
  CHANGELOG.md
  hlint/hlint.dhall
  src/Relude/Extra/Enum.hs
  src/Relude/Extra/Tuple.hs
Labels: extra, hlint, new

#290 [#285] List functions Haddock Table
  CHANGELOG.md
  src/Relude/List.hs
  src/Relude/List/NonEmpty.hs
  src/Relude/List/Reexport.hs
Labels: doc, refactoring

#292 [#291] Archaeology Quest: add @since to EACH function
  CHANGELOG.md
  src/Relude/Applicative.hs
  src/Relude/Bool/Guard.hs
  src/Relude/Container/One.hs
  src/Relude/Extra/Bifunctor.hs
  src/Relude/Extra/CallStack.hs
  src/Relude/Extra/Enum.hs
  src/Relude/Extra/Foldable1.hs
  src/Relude/Extra/Group.hs
  src/Relude/Extra/Lens.hs
  src/Relude/Extra/Map.hs
  src/Relude/Extra/Newtype.hs
  src/Relude/Extra/Tuple.hs
  src/Relude/Extra/Type.hs
  src/Relude/Extra/Validation.hs
  src/Relude/File.hs
  src/Relude/Foldable/Fold.hs
  src/Relude/Functor/Fmap.hs
  src/Relude/Lifted.hs
  src/Relude/Lifted/Terminal.hs
  src/Relude/List/NonEmpty.hs
  src/Relude/Monad.hs
  src/Relude/Monad/Either.hs
  src/Relude/Monad/Trans.hs
  src/Relude/Numeric.hs
  src/Relude/Print.hs
  src/Relude/String/Conversion.hs
Labels: doc

#295 [#293] Add `memptyIfTrue/False` functions
  CHANGELOG.md
  src/Relude/Monoid.hs
Labels: new

#296 [#286] Consistent type for 'readMaybe' and 'readEither'
  CHANGELOG.md
  src/Relude/String.hs
  src/Relude/String/Conversion.hs
Labels: enhancement

#297 [#294] Add atomicModifyIORef_ and atomicModifyIORef'_
  .hlint.yaml
  CHANGELOG.md
  hlint/hlint.dhall
  src/Relude/Lifted/IORef.hs
Labels: new

#298 Update dependency graph, patch instructions
  README.md
  relude-dependency-graph.png
Labels: doc

#299 Fix name of product in haddock (was 'production')
  src/Relude/Foldable/Fold.hs
Labels: doc
