Repository kowainik/relude, pull requests merged in 2021-03, with the labels that each got.

#348 [#311] Add `maybeAt`, `!!?` with its arguments flipped
  CHANGELOG.md
  src/Relude/List.hs
Labels: new

#350 Allow bytestring-0.11
  relude.cabal
Labels: enhancement

#352 [#346] Implement `ordNub` using `nubOrd` from `containers` for better efficiency
  CHANGELOG.md
  README.md
  benchmark/Main.hs
  src/Relude/Nub.hs
Labels: enhancement, reexport

#354 [#347] Add `ordNubOn`
  CHANGELOG.md
  src/Relude/Nub.hs
Labels: new

#355 [#268] Drop GHC 8.0.2 support
  .github/workflows/ci.yml
  CHANGELOG.md
  README.md
  relude.cabal
  src/Relude/Applicative.hs
  src/Relude/Base.hs
  src/Relude/Debug.hs
  src/Relude/Exception.hs
  src/Relude/Extra/Newtype.hs
  src/Relude/Extra/Type.hs
  src/Relude/Foldable/Reexport.hs
  src/Relude/Monad/Either.hs
  src/Relude/Monad/Trans.hs
Labels: CI, doc

#356 [#317] Minor documentation improvements (part 3)
  .hlint.yaml
  README.md
  hlint/hlint.dhall
  src/Relude.hs
  src/Relude/Applicative.hs
  src/Relude/Bool.hs
  src/Relude/Bool/Guard.hs
  src/Relude/Bool/Reexport.hs
  src/Relude/Container.hs
  src/Relude/Container/One.hs
  src/Relude/Container/Reexport.hs
  src/Relude/DeepSeq.hs
  src/Relude/Exception.hs
  src/Relude/Extra.hs
  src/Relude/Extra/Bifunctor.hs
  src/Relude/Extra/CallStack.hs
  src/Relude/Extra/Enum.hs
  src/Relude/Extra/Foldable.hs
  src/Relude/Extra/Foldable1.hs
  src/Relude/Extra/Group.hs
  src/Relude/Extra/Lens.hs
  src/Relude/Extra/Map.hs
  src/Relude/Extra/Tuple.hs
  src/Relude/File.hs
  src/Relude/Foldable.hs
  src/Relude/Foldable/Fold.hs
  src/Relude/Function.hs
  src/Relude/Functor.hs
  src/Relude/Functor/Fmap.hs
  src/Relude/Functor/Reexport.hs
  src/Relude/Lifted.hs
  src/Relude/Lifted/Concurrent.hs
  src/Relude/Lifted/Env.hs
  src/Relude/Lifted/Exit.hs
  src/Relude/Lifted/File.hs
  src/Relude/Lifted/Handle.hs
  src/Relude/Lifted/IORef.hs
  src/Relude/Lifted/Terminal.hs
  src/Relude/List.hs
  src/Relude/List/NonEmpty.hs
  src/Relude/List/Reexport.hs
  src/Relude/Monad.hs
  src/Relude/Monad/Maybe.hs
  src/Relude/Monad/Reexport.hs
  src/Relude/Monoid.hs
  src/Relude/Numeric.hs
  src/Relude/Print.hs
  src/Relude/String.hs
  src/Relude/String/Conversion.hs
  src/Relude/String/Reexport.hs
  src/Relude/Unsafe.hs
Labels: doc

#357 [#280] Move to 'cabal-version: 3.0'
  relude.cabal
Labels: doc

#358 [#353] Reexport external libraries
  CHANGELOG.md
  README.md
  relude.cabal
  src/Relude.hs
Labels: reexport

#359 [#304] Improve documentation for the 'Relude.Debug' module
  src/Relude/Debug.hs
Labels: doc

#360 [#270] Standardise some Extra API
  CHANGELOG.md
  relude.cabal
  src/Relude.hs
  src/Relude/Base.hs
  src/Relude/Debug.hs
  src/Relude/Enum.hs
  src/Relude/Extra/Enum.hs
  src/Relude/Extra/Tuple.hs
  src/Relude/Monoid.hs
  src/Relude/Numeric.hs
Labels: question, reexport

#362 [#361] Move benchmarks to criterion instead of gauge
  benchmark/Main.hs
  relude.cabal
Labels: benchmarks

#364 [#345] Support GHC-9.0
  .github/workflows/ci.yml
  CHANGELOG.md
  relude.cabal
  src/Relude/Lifted/File.hs
  stack.yaml
Labels: CI, enhancement

#365 Prepare the 1.0.0.0 release
  .github/workflows/ci.yml
  CHANGELOG.md
  README.md
  relude.cabal
  src/Relude/Debug.hs
  src/Relude/Enum.hs
  src/Relude/Extra/Foldable.hs
  src/Relude/Extra/Foldable1.hs
  src/Relude/Lifted/Env.hs
  src/Relude/Lifted/File.hs
  src/Relude/Lifted/Handle.hs
  src/Relude/List.hs
  src/Relude/Monad.hs
  src/Relude/Nub.hs
Labels: doc

#366 Minor docs fixes
  CHANGELOG.md
  relude.cabal
  src/Relude/Enum.hs
  src/Relude/Extra/Foldable1.hs
  src/Relude/Extra/Lens.hs
Labels: doc

#367 Correct typo in README
  README.md
Labels: doc

#369 Build with working GHC on Windows and macOS
  .github/workflows/ci.yml
Labels: CI
