Repository kowainik/relude, pull requests merged in 2022-04, with the labels that each got.

#391 Future-proof re-exports from Data.Eq
  relude.cabal
  src/Relude/Base.hs
Labels: reexport

#399 Raise upper bound on `hashable`
  CHANGELOG.md
  relude.cabal
  src/Relude/Nub.hs
Labels: dependency

#407 [#372] Warn on usages of`readFileText` and `writeFileText`
  CHANGELOG.md
  src/Relude/File.hs
  src/Relude/Lifted/File.hs
Labels: enhancement, doc

#410 Switch from criterion to tasty-bench
  CHANGELOG.md
  benchmark/Main.hs
  relude.cabal
Labels: benchmarks
